USE SCHEMA DW;

WITH TMP_INVOICE AS (
    SELECT
        i.InvoiceId AS INVOICE_ID,
        i.CustomerId AS CUSTOMER_ID,
        TO_NUMBER(TO_CHAR(CAST(i.InvoiceDate AS DATE),'YYYYMMDD')) AS DATE_KEY,
        i.Total AS TOTAL_SALE_AMT,
        1 AS SOURCE_ID
    FROM CHINOOK_DB.STAGE.INVOICE i
)
INSERT INTO SALES_FACT
    (SALES_KEY, CUSTOMER_KEY, INVOICE_ID, DATE_DIM_KEY, TOTAL_SALE_AMT, SOURCE_ID, DATE_TO_WAREHOUSE)
SELECT
    SALES_FACT_SEQ.NEXTVAL,
    c.CUSTOMER_KEY,
    x.INVOICE_ID,
    d.DATE_KEY,
    x.TOTAL_SALE_AMT,
    x.SOURCE_ID,
    CURRENT_TIMESTAMP()
FROM TMP_INVOICE x
JOIN DW.DATE_DIM d ON d.DATE_KEY = x.DATE_KEY
JOIN DW.CUSTOMER_DIM c ON c.CUSTOMER_ID = x.CUSTOMER_ID;
