USE SCHEMA DW;

-- Populate 10 years of dates (2010–2019)
WITH seq AS (
    SELECT DATEADD(day, SEQ4(), '2010-01-01') AS d
    FROM TABLE(GENERATOR(ROWCOUNT => 3650))
)
INSERT INTO DATE_DIM
SELECT
    TO_NUMBER(TO_CHAR(d,'YYYYMMDD')) AS DATE_KEY,
    d AS FULL_DATE,
    DAY(d) AS DAY_NUM,
    MONTH(d) AS MONTH_NUM,
    YEAR(d) AS YEAR_NUM,
    TO_VARCHAR(d,'DY') AS WEEKDAY_ABBR,
    IFF(DAYOFWEEKISO(d) IN (6,7),'Y','N') AS IS_WEEKEND
FROM seq;
