USE SCHEMA DW;

MERGE INTO ARTIST_DIM d
USING (
    SELECT
        ArtistId AS ARTIST_ID,
        Name AS ARTIST_NAME,
        'ADF' AS SOURCE_ID
    FROM CHINOOK_DB.STAGE.ARTIST
) s
ON d.ARTIST_ID = s.ARTIST_ID
WHEN MATCHED AND NVL(d.ARTIST_NAME,'') <> NVL(s.ARTIST_NAME,'') THEN
    UPDATE SET ARTIST_NAME = s.ARTIST_NAME, DATE_TO_WAREHOUSE = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN
    INSERT (ARTIST_KEY, ARTIST_ID, ARTIST_NAME, SOURCE_ID, DATE_TO_WAREHOUSE)
    VALUES (ARTIST_DIM_SEQ.NEXTVAL, s.ARTIST_ID, s.ARTIST_NAME, s.SOURCE_ID, CURRENT_TIMESTAMP());
