-- Stage table counts
SELECT 'CUSTOMER' AS TBL, COUNT(*) CNT FROM STAGE.CUSTOMER
UNION ALL SELECT 'ARTIST', COUNT(*) FROM STAGE.ARTIST
UNION ALL SELECT 'ALBUM', COUNT(*) FROM STAGE.ALBUM
UNION ALL SELECT 'INVOICE', COUNT(*) FROM STAGE.INVOICE;

-- DW dimension counts
SELECT 'DATE_DIM', COUNT(*) FROM DW.DATE_DIM
UNION ALL SELECT 'TIME_DIM', COUNT(*) FROM DW.TIME_DIM
UNION ALL SELECT 'CUSTOMER_DIM', COUNT(*) FROM DW.CUSTOMER_DIM
UNION ALL SELECT 'ARTIST_DIM', COUNT(*) FROM DW.ARTIST_DIM;

-- Fact table validation
SELECT COUNT(*) AS SALES_FACT_ROWS FROM DW.SALES_FACT;

-- Optional preview
SELECT * FROM DW.SALES_FACT LIMIT 20;
