USE DATABASE CHINOOK_DB;
CREATE SCHEMA IF NOT EXISTS DW;

-- DATE DIM
CREATE OR REPLACE TABLE DW.DATE_DIM (
    DATE_KEY NUMBER(8) PRIMARY KEY,
    FULL_DATE DATE,
    DAY_NUM NUMBER,
    MONTH_NUM NUMBER,
    YEAR_NUM NUMBER,
    WEEKDAY_ABBR VARCHAR(10),
    IS_WEEKEND VARCHAR(1)
);

-- TIME DIM
CREATE OR REPLACE TABLE DW.TIME_DIM (
    TIME_KEY NUMBER(4) PRIMARY KEY,
    HOUR_NUM INT,
    MINUTE_NUM INT,
    TIME_24_HR STRING
);

-- CUSTOMER DIM
CREATE OR REPLACE TABLE DW.CUSTOMER_DIM (
    CUSTOMER_KEY NUMBER PRIMARY KEY,
    CUSTOMER_ID INT,
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    COMPANY_NAME VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    COUNTRY VARCHAR(100),
    ZIP_CODE VARCHAR(20),
    SUPPORT_REP_ID INT,
    SOURCE_ID VARCHAR(10),
    CUSTOMER_HASH VARCHAR(64),
    DATE_TO_WAREHOUSE TIMESTAMP_NTZ
);
CREATE OR REPLACE SEQUENCE CUSTOMER_DIM_SEQ START = 1 INCREMENT = 1;

-- ARTIST DIM
CREATE OR REPLACE TABLE DW.ARTIST_DIM (
    ARTIST_KEY NUMBER PRIMARY KEY,
    ARTIST_ID INT,
    ARTIST_NAME VARCHAR(100),
    SOURCE_ID VARCHAR(10),
    DATE_TO_WAREHOUSE TIMESTAMP_NTZ
);
CREATE OR REPLACE SEQUENCE ARTIST_DIM_SEQ START = 1 INCREMENT = 1;

-- FACT
CREATE OR REPLACE TABLE DW.SALES_FACT (
    SALES_KEY NUMBER PRIMARY KEY,
    CUSTOMER_KEY NUMBER,
    INVOICE_ID INT,
    DATE_DIM_KEY NUMBER,
    TOTAL_SALE_AMT NUMBER(10,2),
    SOURCE_ID NUMBER,
    DATE_TO_WAREHOUSE TIMESTAMP_NTZ
);
CREATE OR REPLACE SEQUENCE SALES_FACT_SEQ START = 1 INCREMENT = 1;
