USE SCHEMA DW;

-- 1440 minutes in a day
INSERT INTO TIME_DIM
SELECT
    (H*100)+M AS TIME_KEY,
    H AS HOUR_NUM,
    M AS MINUTE_NUM,
    LPAD(H::STRING,2,'0') || ':' || LPAD(M::STRING,2,'0') AS TIME_24_HR
FROM (
  SELECT SEQ4() AS N FROM TABLE(GENERATOR(ROWCOUNT => 1440))
),
LATERAL (
  SELECT (N/60)::INT AS H, (N%60)::INT AS M
);
